.TH BFINDEX "1" "April 2003"
.SH NAME
bfindex \- nodelist compiler for bforce
.SH SYNOPSYS
\fBbfindex [-fh]\fR

.SH DESCRIPTION
\fBbfindex\fP is a nodelist compiler for BinkleyForce FTN mailer. 
.SH OPTIONS
\fB\-f\fR
force nodelist compiling
.P
\fB-h\fR
show help message
.SH SEE ALSO
bforce(1),bfstat(1),nlookup(1)
.SH AUTHOR
Bforce was written by Alexander Belkin <adb@newmail.ru>, 2:5020/2120
.P
This manual page was written by Zhenja Kaluta <trinfo@mail.ru>

This is free documentation; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
