.TH BINDEX "1" "April 2003"
.SH NAME
bfstat \- binkley style outbound statistic
.SH SYNOPSYS
\fBbfstat [-afhprst] [-n \fInumber\fB]\fR
.SH DESCRIPTION
\fBbfstat\fP help you to see your outbound statistic in human readable
form. 
.SH OPTIONS
\fB\-a\fR
sort by FTN address (default)
.P
\fB\-c\fR
print incoming/outgoing calls statistic
.P
\fB\-f\fR
disable queue sorting
.P
\fB\-n \fInumber\fR
don't print more than <number> systems
.P
\fB\-p\fR
print sizes in human readable format
.P
\fB\-r\fR
reverse order while sorting
.P
\fB\-s\fR
sort by total files size
.P
\fB\-t\fR
disable total sizes printing
.P
\fB-h\fR
show help message
.SH SEE ALSO
bforce(1),bindex(1),nlookup(1)
.SH AUTHOR
Bforce was written by Alexander Belkin <adb@newmail.ru>, 2:5020/2120
.P
This manual page was written by Zhenja Kaluta <trinfo@mail.ru>
.P
Revision 2 by Evgeniy Kozhuhovskiy <e.kozhuhovskiy@gmail.com>
This is free documentation; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
