.TH OUTMAN "1" "November 2004"
.SH NAME
outman \- creates polls, file requests and attach files in aso and bso
.SH SYNOPSIS
.B outman
\fI<\fR[\fIpoll|freq|send\fR]\fI> \fR[\fIoptions\fR] \fI<address> \fR[\fIfiles\fR]
.SH DESCRIPTION
.SS "options:"
.TP
\fB\-hold\fR
set hold flavor
.TP
\fB\-normal\fR
set normal flavor (default)
.TP
\fB\-crash\fR
set crash flavor
.TP
\fB\-kill\fR
kill files after send
.HP
\fB\-truncate\fR truncate files after send
.PP
Mail bug reports to <e.kozhuhovskiy@gmail.com>
.SH "SEE ALSO"
bfindex(1), bfstat(1), nlookup(1), bforce(1)
.SH AUTHOR
Bforce was written by Alexander Belkin <adb@newmail.ru>, 2:5020/2120
.P
This manual page was written by Evgeniy Kozhuhovskiy <e.kozhuhovskiy@gmail.com>

This is free documentation; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.

